### ISSUE TITLE
spnego "only one authentication iteration allowed"

### ISSUE THREAD

**Issue by bazsi** [stnoonan/spnego-http-auth-nginx-module#70] opened 2016-12-28 14:51 UTC
Hi,
I was trying to enable GSSAPI based authentication with an MIT krb5 kdc, nginx and curl, e.g. no Windows AD was present. As I see GSS_S_CONTINUE is not handled, but instead the error message in $SUBJECT is displayed.

Is there any reason in not handling CONTINUE as a minor status? Is there a specific algorithm/setting in the KDC that would generate only a single GSSAPI exchange?

Thanks in advance.

**Comment by lordmauve** [comment] 2018-01-16 14:25
Is this a duplicate of #64?

**Comment by bazsi** [comment] 2018-01-16 15:29
Honestly, this was a long time ago, but I did get that error message, otherwise I wouldn't have looked up the code.

And yes, this definitely seems to be a duplicate.

**Comment by stnoonan** [comment] 2020-04-04 22:21
Duplicate of #64

**Closed by stnoonan** 2020-04-04 22:21 UTC
Labels: duplicate
